version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=qrninja
      - DB_PORT=5432

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qrninja
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
